name: CI/CD Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug secret presence
      run: |
        echo "Checking required secrets..."
        
        if [ -z "${{ secrets.SERVER_IP }}" ]; then
          echo "❌ SERVER_IP is NOT set"
          exit 1
        else
          echo "✅ SERVER_IP is set"
        fi

        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "❌ SSH_PRIVATE_KEY is NOT set"
          exit 1
        else
          echo "✅ SSH_PRIVATE_KEY is set"
        fi

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

    - name: Build and Run Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
          cd git_local/djk_kalender
          git pull
          docker compose down || true
          docker compose up -d --build
        EOF
